version: '2.1'

services:
  nginx:
    image: nginx:1.13.6-alpine
    ports:
      - "80:80"
      - "443:443"
    # extra_hosts:
    #   - "localhost:10.0.2.2"
    volumes:
      - "./.ssl:/.ssl"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/locationblock.conf:/etc/nginx/locationblock.conf"
      - "./nginx/sites-enabled:/etc/nginx/sites-enabled"
      - "./nginx/sites-available:/etc/nginx/sites-available"
  
  portainer:
    image: portainer/portainer
    ports:
      - "4667:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
